### ISSUE TITLE
PC version

### ISSUE THREAD

**Issue by AluminYu** [timschneeb/RootlessJamesDSP#223]
Are there any plans to make a PC version?

I'd love to see something like it. There are many audio processing options for PC, but few are so friendly, easy to use and accessible as this one - it's just too good:)

**Comment by xodus2002** [comment]
There's EasyEffect which is for Pipewire (on Linux), on Windows it's the sound driver settings

**Comment by ascendbeing** [comment]
> There's EasyEffect which is for Pipewire (on Linux), on Windows it's the sound driver settings

There's a windows one whose name starts with an F or an X, iirc. It's on windows store for free but it's a normal windows 32 bit style application, which has features like EQ and increasing the gain beyond what the volume control allows one to do.

**Comment by timschneeb** [comment]
I've already created a Linux port for JamesDSP: https://github.com/Audio4Linux/JDSP4Linux/

I don't have plans for a Windows port, though. On Windows, there's also EqualizerAPO for audio effects.
