### ISSUE TITLE
Legacy mode from wavelet

### ISSUE THREAD

**Issue by Sensex00** [timschneeb/RootlessJamesDSP#225]
I think we should introduce legacy mode in the app apart from shizuku it will be great for users both old and new to quickly get this app working
It will come in handy maybe some features would not usable but it's not a bad feature to have have 
Apart from dump permission

**Comment by timschneeb** [comment]
As mentioned in the README:

> Regular rootless audio effect apps on the Play Store all essentially work the same way: Android has several default audio effects built into its operating system that these apps can use without any special permissions. Here's a list of those: https://developer.android.com/reference/android/media/audiofx/AudioEffect.

> Being restricted to these default built-in audio effects is problematic if you want to implement any advanced custom effects such as Viper or JDSP, because Android does not allow apps to access & modify the audio stream directly.

> To work around this problem, RootlessJamesDSP uses a bunch of tricks to gain full access to the audio stream of other apps. This is done via Android's internal audio capture. This allows RootlessJamesDSP to apply its custom audio effects directly without relying on Android's built-in effects.

> Unfortunately, these tricks are not 100% reliable and introduce some limitations. Apps such as Spotify block internal audio capture (they don't want people to record their songs), and because of that, RootlessJamesDSP cannot directly access the audio stream of that app. This is the reason why a special patch is required to disable this DRM restriction inside Spotify's app. Patches for other apps with these DRM restrictions do not exist, but are possible to do.


Wavelet can only use Android's bundled audio effects and works differently from RootlessJamesDSP because of that.

RootlessJamesDSP installs a custom audio effect, and those cannot use legacy mode without root access.
