### ISSUE TITLE
Add new Android 15 warning

### ISSUE THREAD

**Issue by Laserology** [timschneeb/RootlessJamesDSP#243]
In android 15, a new setting called "Disable screen share protections" is disabled by default, which causes notifications to appear broken/weird. This setting gets turned off by default, even for devices upgrading from A14. There is no other indication of why notifications might be broken. This app triggers the new setting because it technically uses part of the screen share service.

My request is that you add a warning to the app, even for existing users, as it would be the only indicator.

**Comment by pflanzenandi** [comment]
Wow, what a coincident that I've found this post. I was convinced my Android 15 GrapheneOS installation was broken.
After disabling named screen protection and restarting all my notifications worked as intended. 

Unfortunately I think @timschneeb stopped working on this project for now.

**Comment by timschneeb** [comment]
>Unfortunately I think @timschneeb stopped working on this project for now.

Yeah, I have been inactive with this project this year. 

>In android 15, a new setting called "Disable screen share protections" is disabled by default, which causes notifications to appear broken/weird. 

I've added a warning message for Android 15 to the app that has instructions for the workaround: https://github.com/timschneeb/RootlessJamesDSP/releases/tag/v1.6.9. The update should appear on Google Play & F-Droid in a few days.

**Comment by cwayne1989** [comment]
> > Unfortunately I think @timschneeb stopped working on this project for now.
> 
> Yeah, I have been inactive with this project this year.
> 
> > In android 15, a new setting called "Disable screen share protections" is disabled by default, which causes notifications to appear broken/weird.
> 
> I've added a warning message for Android 15 to the app that has instructions for the workaround: https://github.com/timschneeb/RootlessJamesDSP/releases/tag/v1.6.9. The update should appear on Google Play & F-Droid in a few days.

Man I just wanted to say Thank you for porting this stuff over for none root users. You really are a godsend man, because as someone that used Viper4Android back in the day, JamesDSP is the only thing that even REMOTELY comes close to being as good. 
That's honestly the one thing I miss about rooting the most, is Viper4Android.
