### ISSUE TITLE
Version 1.69 not found

### ISSUE THREAD

**Issue by kimutimuti** [timschneeb/RootlessJamesDSP#251]
I've never used GitHub, and I'm not good at English, so please forgive me if my question is misunderstood.

It was written in the release column "released version 1.69" four hours before I asked this question, but I couldn't find the characters for version 1.69 in both the play store and the F-Droid.

Is this a region issue or something? My terminal is a Google Pixel 8, version 15, and the region is Japanese, but the play store version is the latest version, so I think there is no problem.

I've been looking forward to it for a long time, so if this is a problem in the region, I want an apk file, even if the language is only English.

I hope someone will answer my question.
This article was written using machine translation.

**Comment by techboote** [comment]
I think it will appear in a few days as the developer mentioned on the other thread.

**Comment by kimutimuti** [comment]
Was that so! Thank you for letting me know!
