### ISSUE TITLE
Latest stops at shizuku permission 

### ISSUE THREAD

**Issue by jairjacom** [timschneeb/RootlessJamesDSP#254]
Although per the app notes, I don't believe it's supposed to work on Android 15. Previous version to this release used to work with its quirks (version from fdroid). The quirks (every now and then it would stop while skipping a song from YouTube Music, clicking the app will resume its processing playing the song fine). Now, on latest release from play store, app stops at the shizuku permission, it doesn't let you go to next screen of the initial setup, a pop-up window shows saying wait or close, after a second or two app force closes. It seems it's getting killed. I tried both versions on my pixel 9 android 15.

**Comment by NedH13** [comment]
Yep I am facing the same problem

**Comment by jairjacom** [comment]
Let's hope dev can check code and hopefully let us use this great app once again.

**Comment by timschneeb** [comment]
Should be fixed in https://github.com/timschneeb/RootlessJamesDSP/releases/tag/v1.6.10. The update will appear in a few days on Google Play and F-Droid. Until then, you can still use the manual ADB setup method to complete the setup.
