### ISSUE TITLE
v1.6.12 (Hotfix) didn't request 'PROJECT_MEDIA' permission 

### ISSUE THREAD

**Issue by pflanzenandi** [timschneeb/RootlessJamesDSP#264]
After installation I wasn't asked to grant named permission. 
Does this work automatically in the background?

**Comment by timschneeb** [comment]
The permission is automatically granted using Shizuku/ADB.

Most users already had this (previously optional) permission granted before this update. The latest update just makes it mandatory on Android 15 due to new restrictions.
